### ISSUE TITLE
Issue entering trunk after placing others in and out of trunk.

### ISSUE THREAD

**Issue by TheCocoNutHead** [S1nScripts/s1n_carryandhideintrunk#18]
By default you get the target option to enter the vehicle trunk. When you carry a player you are able to put them in the trunk, After you remove them and even uncarry them the option to hide yourself in the trunk doesn't appear anymore but yet i'm still able to place the other player in the trunk.

**Comment by s1nyx** [comment]
@m1ch433l Hi could you maybe look into it ?

**Comment by m1ch433l** [comment]
> @m1ch433l Hi could you maybe look into it ?
I will check it
