### ISSUE TITLE
> > > So far so good just found a new issue.

### ISSUE THREAD

**Issue by TheCocoNutHead** [S1nScripts/s1n_carryandhideintrunk#25]
> > > So far so good just found a new issue.
> > > So you carry the player and place them in the trunk the STOP CARRY notification remains on screen and when you use the button the player gets removed from the trunk but is frozen and can't move. Until you place them in vehicle again and release them.
> > > Maybe look so it removes that when the player has been placed in the trunk. Also didnt test this but possibly reset for when example vehicle is deleted while player is trunk so they aren't stuck or frozen.
> > > https://medal.tv/games/gta-v/clips/1PbilX31a0RdWi/d13371JTwcJg?invite=cr-MSxRejYsMTEwMjAxMjk5LA
> > 
> > 
> > I think it's easy just don't press that's all, but I'll look into it
> 
> Have there been any updates?

Hey, 

No.
Please create an issue with a recap. Avoid commenting on PR merged.

Thanks and have a nice day.

_Originally posted by @s1nyx in https://github.com/S1nScripts/s1n_carryandhideintrunk/issues/19#issuecomment-1907772679_

**Comment by lush0n3** [comment]
Hello, good morning, is there a solution for this problem?

By the way, very good script, I appreciate you sharing it with the community!

**Comment by s1nyx** [comment]
Hi @lush0n3 @TheCocoNutHead The issue should now be fixed with the version 1.5.1. 

Have a nice day.
