### ISSUE TITLE
script issues

### ISSUE THREAD

**Issue by EJJ04** [S1nScripts/s1n_carryandhideintrunk#5]
Hey,
when i am in trunk there is a help text which says “[E] - Get out of the Trunk” but when pressing E nothing happens and after i left the trunk through ox_target i can walk through the hole car, seems to has no hitbox. And furthermore i cant get in Trunk again, i only get the error that someone is already in car, after restart i can get into the car once.

**Comment by m1ch433l** [comment]
> Hey, when i am in trunk there is a help text which says “[E] - Get out of the Trunk” but when pressing E nothing happens and after i left the trunk through ox_target i can walk through the hole car, seems to has no hitbox. And furthermore i cant get in Trunk again, i only get the error that someone is already in car, after restart i can get into the car once.

Install newer version, my PR with fix for leaving and entering trunk again was merged so its fixed. But the "E" textui is still not fixed.

**Comment by m1ch433l** [comment]
Already fixed i think

**Comment by s1nyx** [comment]
Hi @EJJ04 can you check ?

**Comment by m1ch433l** [comment]
> Hi @EJJ04 can you check ?

Checked working but i found other bugs, working on PR
