### ISSUE TITLE
Can't carry player dead peds

### ISSUE THREAD

**Issue by s1nyx** [S1nScripts/s1n_carryandhideintrunk#6]
We should add a feature to add the possibility for carrying player dead peds

**Comment by m1ch433l** [comment]
It's not possible? I will look into that and work on that

**Comment by s1nyx** [comment]
> It's not possible? I will look into that and work on that

Awesome :)

**Comment by m1ch433l** [comment]
Do you mean like we should add feature that will allow player to carry dead NPC?

**Comment by Everosome** [comment]
Carry dead players not npcs :)

**Comment by m1ch433l** [comment]
Please provide me with clip where u cant carry dead players, tried it and working :)

**Comment by s1nyx** [comment]
Maybe you got a custom script that handle players death ? @Everosome

**Comment by m1ch433l** [comment]
QBX / QB working

**Comment by s1nyx** [comment]
> QBX / QB working

If it works for QB, it's the same for ESX unless you have a custom script that overwrite players dead peds.
