### ISSUE TITLE
Screen blackout while in trunk

### ISSUE THREAD

**Issue by m1ch433l** [S1nScripts/s1n_carryandhideintrunk#8]
My friend and I thought of implementing a function that would darken the player's screen while he was in the trunk of the vehicle (whether someone put him there or entered it himself). As soon as the vehicle had an open trunk, the player would see outside, if someone closed it again, he would see only darkness.

I will try to work on it in my spare time and give it as a PR

**Comment by s1nyx** [comment]
Awesome!
